# Generated by Django 5.2.11 on 2026-02-25 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade value (0-20 scale)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when grade was first entered",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when grade was last updated"
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        help_text="User who entered this grade",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grades_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Semester in which the grade was given",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grades",
                        to="students.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who received this grade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject for which the grade was given",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grades",
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "db_table": "academic_grade",
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Previous grade value", max_digits=5
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        decimal_places=2, help_text="New grade value", max_digits=5
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of modification"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for the modification"
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="Grade that was modified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="grades.grade",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who modified the grade",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grade_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grade histories",
                "db_table": "academic_grade_history",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student"], name="academic_gr_student_bf905a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["subject"], name="academic_gr_subject_251b8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["semester"], name="academic_gr_semeste_87b1c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["entered_by"], name="academic_gr_entered_64ba71_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0), ("value__lte", 20)),
                name="check_grade_value_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "subject", "semester")},
        ),
        migrations.AddIndex(
            model_name="gradehistory",
            index=models.Index(fields=["grade"], name="academic_gr_grade_i_c1c0f9_idx"),
        ),
        migrations.AddIndex(
            model_name="gradehistory",
            index=models.Index(
                fields=["modified_at"], name="academic_gr_modifie_4e5f1a_idx"
            ),
        ),
    ]
