# Generated by Django 5.2.11 on 2026-02-25 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Class name (e.g., "Class A", "Grade 10")',
                        max_length=100,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text='Academic level (e.g., "Level 1", "Grade 10")',
                        max_length=50,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text='Academic year in format YYYY-YYYY (e.g., "2024-2025")',
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Classes",
                "db_table": "academic_class",
                "indexes": [
                    models.Index(
                        fields=["academic_year"], name="academic_cl_academi_196b63_idx"
                    )
                ],
                "unique_together": {("name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Semester name (e.g., "Semester 1", "Fall 2024")',
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(help_text="Semester start date")),
                ("end_date", models.DateField(help_text="Semester end date")),
                (
                    "academic_year",
                    models.CharField(
                        help_text='Academic year in format YYYY-YYYY (e.g., "2024-2025")',
                        max_length=9,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the current active semester",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "academic_semester",
                "indexes": [
                    models.Index(
                        fields=["academic_year"], name="academic_se_academi_7b0f45_idx"
                    ),
                    models.Index(
                        fields=["is_current"], name="academic_se_is_curr_38e0cd_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="check_semester_dates",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Subject name (e.g., "Mathematics", "Physics")',
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Unique subject code (e.g., "MATH101")',
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Subject coefficient for weighted average calculation",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(9.99),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Subject description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "academic_subject",
                "indexes": [
                    models.Index(fields=["code"], name="academic_su_code_d89c14_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Unique student identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Student first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Student last name", max_length=100),
                ),
                (
                    "enrollment_date",
                    models.DateField(help_text="Date when student enrolled"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Student photo",
                        null=True,
                        upload_to="students/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the student is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_assigned",
                    models.ForeignKey(
                        help_text="Class to which the student belongs",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="students",
                        to="students.class",
                    ),
                ),
            ],
            options={
                "db_table": "academic_student",
                "indexes": [
                    models.Index(
                        fields=["class_assigned"], name="academic_st_class_a_562f3e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="academic_st_is_acti_53fe2f_idx"
                    ),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="academic_st_last_na_e96824_idx",
                    ),
                    models.Index(
                        fields=["student_id"], name="academic_st_student_ea42fc_idx"
                    ),
                ],
            },
        ),
    ]
