# Generated by Django 5.2.11 on 2026-02-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average grade (subject-specific or overall weighted average)",
                        max_digits=5,
                    ),
                ),
                (
                    "standard_deviation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard deviation of grades (for class-level analysis)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "progression_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage change from previous semester",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "class_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Student rank within their class",
                        null=True,
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when metrics were last calculated",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Semester for which metrics are calculated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_indicators",
                        to="students.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student for whom metrics are calculated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_indicators",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject for which metrics are calculated (null for overall performance)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_indicators",
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "db_table": "academic_performance_indicator",
                "indexes": [
                    models.Index(
                        fields=["student"], name="academic_pe_student_8fc3e3_idx"
                    ),
                    models.Index(
                        fields=["semester"], name="academic_pe_semeste_1be4d1_idx"
                    ),
                    models.Index(
                        fields=["subject"], name="academic_pe_subject_e04093_idx"
                    ),
                ],
                "unique_together": {("student", "semester", "subject")},
            },
        ),
    ]
