# Generated by Django 5.2.11 on 2026-02-25 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceindicator",
            name="average",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Average grade (subject-specific or overall)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="performanceindicator",
            name="calculated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of last calculation"
            ),
        ),
        migrations.AlterField(
            model_name="performanceindicator",
            name="semester",
            field=models.ForeignKey(
                help_text="Semester for which this indicator applies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_indicators",
                to="students.semester",
            ),
        ),
        migrations.AlterField(
            model_name="performanceindicator",
            name="standard_deviation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation (for class-level statistics)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="performanceindicator",
            name="student",
            field=models.ForeignKey(
                help_text="Student for whom this indicator is calculated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_indicators",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="performanceindicator",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject (null for overall indicators)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_indicators",
                to="students.subject",
            ),
        ),
    ]
