import React, { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FileText, Download, Filter } from 'lucide-react';

interface Student {
  id: number;
  student_id: string;
  first_name: string;
  last_name: string;
  class_name: string;
}

export default function Reports() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/students')
      .then(res => res.json())
      .then(data => {
        setStudents(data);
        setLoading(false);
      });
  }, []);

  const generateReport = async (student: Student) => {
    try {
      // Fetch student grades
      const res = await fetch(`/api/grades/student/${student.id}`);
      const grades = await res.json();

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.text('Academic Performance Report', 105, 20, { align: 'center' });
      
      doc.setFontSize(12);
      doc.text(`Student: ${student.last_name} ${student.first_name} (${student.student_id})`, 14, 40);
      doc.text(`Class: ${student.class_name}`, 14, 48);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 56);

      // Grades Table
      const tableData = grades.map((g: any) => [
        g.code,
        g.course_name,
        g.type.toUpperCase(),
        g.score,
        g.weight
      ]);

      autoTable(doc, {
        startY: 65,
        head: [['Code', 'Course', 'Type', 'Score', 'Weight']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [63, 81, 181] },
      });

      // Calculate Average
      let totalScore = 0;
      let totalWeight = 0;
      grades.forEach((g: any) => {
        totalScore += g.score * g.weight;
        totalWeight += g.weight;
      });
      const average = totalWeight > 0 ? (totalScore / totalWeight).toFixed(2) : 'N/A';

      // Summary
      const finalY = (doc as any).lastAutoTable.finalY + 20;
      doc.setFontSize(14);
      doc.text(`Weighted Average: ${average} / 20`, 14, finalY);

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text('Generated by APAS - Academic Performance Analytics System', 105, 280, { align: 'center' });

      doc.save(`Report_${student.student_id}.pdf`);
    } catch (err) {
      console.error('Error generating PDF:', err);
      alert('Failed to generate report');
    }
  };

  if (loading) return <div>Loading...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-slate-900">Academic Reports</h1>
        <div className="flex gap-2">
          <button className="bg-white border border-slate-300 text-slate-700 px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-slate-50 transition-colors">
            <Filter className="w-4 h-4" />
            Filter
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {students.map((student) => (
          <div key={student.id} className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow">
            <div className="flex items-start justify-between mb-4">
              <div className="w-10 h-10 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold">
                {student.first_name[0]}{student.last_name[0]}
              </div>
              <span className="text-xs font-mono text-slate-400">{student.student_id}</span>
            </div>
            
            <h3 className="font-semibold text-slate-900">{student.last_name} {student.first_name}</h3>
            <p className="text-sm text-slate-500 mb-6">{student.class_name}</p>

            <button 
              onClick={() => generateReport(student)}
              className="w-full bg-slate-900 text-white py-2 rounded-lg flex items-center justify-center gap-2 hover:bg-slate-800 transition-colors text-sm font-medium"
            >
              <Download className="w-4 h-4" />
              Download Report
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
